import { relative, join } from 'path';
import type { PreToolInput, HookOutput, PreToolOutput } from './types.js';
import { readState, hasActiveFlow } from './state.js';

// Control plane paths — all relative to project root, always write-protected.
// feat-flow is always installed as a project-scope plugin, so its files land at
// .claude/plugins/feat-flow/ (not .claude/hooks/ which was the old manual path).
const CONTROL_PLANE_PREFIXES = [
  '.feat-flow/',                 // state machine files (project-level)
  '.claude/plugins/feat-flow/', // hook scripts, stage docs, library (plugin install)
];

// gate-token is also read-protected: AI must never see the token
// (token is generated by hook, shown only via systemMessage to user)
const READ_PROTECTED = ['.feat-flow/gate-token'];

// Write tools that carry a file_path
const WRITE_TOOLS = new Set(['Edit', 'Write', 'NotebookEdit']);
// Read-only tools — always allowed even on protected paths
const READ_TOOLS = new Set(['Read', 'Glob', 'Grep', 'LS']);

// Stages where writes are restricted to docs/feat-flows/ and docs/adr/
const DOC_ONLY_STAGES = new Set([
  'stage-1', 'stage-2', 'stage-3', 'stage-4',
  'stage-6', 'stage-7', 'stage-8',
]);

function deny(reason: string): HookOutput {
  const out: PreToolOutput = {
    hookEventName: 'PreToolUse',
    permissionDecision: 'deny',
    permissionDecisionReason: reason,
  };
  return { hookSpecificOutput: out };
}

export async function handlePreToolUse(input: PreToolInput): Promise<HookOutput | null> {
  const { cwd, tool_name, tool_input } = input;

  if (!hasActiveFlow(cwd)) return null;

  // Read tool: allow most paths, but gate-token is read-protected
  if (READ_TOOLS.has(tool_name)) {
    const filePath = (tool_input['file_path'] ?? '') as string;
    const rel = filePath.startsWith(cwd) ? filePath.slice(cwd.length + 1) : filePath.replace(/^\//, '');
    for (const protected_ of READ_PROTECTED) {
      if (rel === protected_ || rel.endsWith('/' + protected_.split('/').pop())) {
        return deny('feat-flow: gate-token 文件受读保护，AI 无法直接读取。token 已通过系统消息告知用户。');
      }
    }
    return null;
  }
  // Bash tool: intercept commands that access critical control-plane files.
  // Read/Write tools are caught by their file_path; Bash uses a command string.
  if (tool_name === 'Bash') {
    const command = (tool_input['command'] ?? '') as string;
    // gate-token must be invisible to AI via any channel
    if (/\.feat-flow\/gate-token/.test(command)) {
      return deny('feat-flow: gate-token 受保护，禁止通过 Bash 访问。token 只能由用户通过系统通知获取。');
    }
    // state.json: block all Bash access (cp/mv/dd/redirect all bypass the write-tool guard)
    if (/\.feat-flow\/state\.json/.test(command)) {
      return deny('feat-flow: 禁止通过 Bash 访问 state.json（控制平面写保护）。');
    }
    // Plugin root: AI must not modify hook scripts, stage docs, or library code.
    // In project-scope install, plugin lives at .claude/plugins/feat-flow/
    if (command.includes('.claude/plugins/feat-flow/')) {
      return deny(
        'feat-flow: 禁止通过 Bash 访问 plugin 内部文件（hooks/stages/lib）。',
      );
    }
    return null;
  }

  // Non-write tools with no file_path to check
  if (!WRITE_TOOLS.has(tool_name)) return null;

  const filePath = (tool_input['file_path'] ?? tool_input['notebook_path'] ?? '') as string;
  if (!filePath) return null;

  // Normalise to relative path
  const rel = filePath.startsWith(cwd)
    ? relative(cwd, filePath)
    : filePath.replace(/^\//, '');

  // Control plane hard deny
  for (const prefix of CONTROL_PLANE_PREFIXES) {
    if (rel.startsWith(prefix) || rel === prefix.replace(/\/$/, '')) {
      return deny(
        `feat-flow: 禁止修改控制平面文件。\n` +
        `路径 ${rel} 受 feat-flow 保护（HMAC 完整性 / 机械执行层 / 工作流定义）。`,
      );
    }
  }

  // Stage-scoped path check
  const state = readState(cwd);
  if (!state) return null;

  const stage = state.current_stage;

  // stage-5 (implementation): allow all paths
  if (stage === 'stage-5') return null;
  // completed: allow all
  if (stage === 'completed') return null;

  if (DOC_ONLY_STAGES.has(stage)) {
    const flowId = state.flow_id;
    const allowed =
      rel.startsWith(`docs/feat-flows/${flowId}/`) ||
      rel.startsWith('docs/feat-flows/') ||
      rel.startsWith('docs/adr/');
    if (!allowed) {
      return deny(
        `feat-flow[${stage}]: 当前阶段只允许写入 docs/feat-flows/ 和 docs/adr/ 路径。\n` +
        `越界写入被拦截：${rel}`,
      );
    }
  }

  return null;
}
